import { Merch } from "../types/Merch";


export const MERCH_DATA: Merch[] =
[
    {
        productId: '1',
        name: "Blue Stage Fright T-shirt - Rick",
        linkName: 'blue-stage-fright-tshirt-rick',
        category: "T-shirt",
        price: 15.99,
        imagePaths: ["Merch/rick1", "Merch/rick2", "Merch/rick3", "Merch/rick4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large", "XXX-Large"],
        sizeAbbreviations: ["sm", "md", "lg", 'xl', 'xxl', 'xxxl'],
        description: "Show your love for Stage Fright in style! This comfortable, high-quality blue T-shirt features the band’s bold logo front and center. Perfect for concerts, casual outings, or just lounging.",
    },
    {
        productId: '2',
        name: "Blue Stage Fright T-shirt - Clark",
        linkName: 'blue-stage-fright-tshirt-clark',
        category: "T-shirt",
        price: 15.99,
        imagePaths: ["Merch/clark1", "Merch/clark2", "Merch/clark3", "Merch/clark4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large", "XXX-Large"],
        sizeAbbreviations: ["sm", "md", "lg", 'xl', 'xxl', 'xxxl'],
        description: "Show your love for Stage Fright in style! This comfortable, high-quality blue T-shirt features the band’s bold logo front and center. Perfect for concerts, casual outings, or just lounging.",
    },
    {
        productId: '3',
        name: "Blue Stage Fright T-shirt - Isaac",
        linkName: 'blue-stage-fright-tshirt-isaac',
        category: "T-shirt",
        price: 15.99,
        imagePaths: ["Merch/isaac1", "Merch/isaac2", "Merch/isaac3", "Merch/isaac4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large", "XXX-Large"],
        sizeAbbreviations: ["sm", "md", "lg", 'xl', 'xxl', 'xxxl'],
        description: "Show your love for Stage Fright in style! This comfortable, high-quality blue T-shirt features the band’s bold logo front and center. Perfect for concerts, casual outings, or just lounging.",
    },
    {
        productId: '4',
        name: "Blue Stage Fright T-shirt - Mattias",
        linkName: 'blue-stage-fright-tshirt-mattias',
        category: "T-shirt",
        price: 15.99,
        imagePaths: ["Merch/mattias1", "Merch/mattias2", "Merch/mattias3", "Merch/mattias4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large", "XXX-Large"],
        sizeAbbreviations: ["sm", "md", "lg", 'xl', 'xxl', 'xxxl'],
        description: "Show your love for Stage Fright in style! This comfortable, high-quality blue T-shirt features the band’s bold logo front and center. Perfect for concerts, casual outings, or just lounging.",
    },
    {
        productId: '5',
        name: "Blue Stage Fright T-shirt",
        linkName: 'blue-stage-fright-t-shirt',
        category: "T-shirt",
        price: 15.99,
        imagePaths: ["Merch/all1", "Merch/all2", "Merch/all3", "Merch/all4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
        sizeAbbreviations: ['sm', 'md', 'lg', 'xl', 'xxl'],
        description: "Show your love for Stage Fright in style! This comfortable, high-quality blue T-shirt features the band’s bold logo front and center. Perfect for concerts, casual outings, or just lounging.",
    },
    {
        productId: '6',
        name: "Blue Stage Fright Hoodie",
        linkName: 'blue-stage-fright-hoodie',
        category: "Hoodie",
        price: 35.99,
        imagePaths: ["Merch/hoodie1", "Merch/hoodie2", "Merch/hoodie3", "Merch/hoodie4"],
        sizes: ["Small", "Medium", "Large", "X-Large", "XX-Large"],
        sizeAbbreviations: ['sm', 'md', 'lg', 'xl', 'xxl'],
        description: "Stay cozy and cool with the Stage Fright blue hoodie. This premium pullover showcases the band’s iconic design on soft, warm fabric—ideal for colder days or late-night gigs. Comes in sizes Small to XX-Large for the perfect fit.",
    },
    {
        productId: '7',
        name: "Stage Fright Sticker",
        linkName: 'stage-fright-sticker',
        category: "sticker",
        price: 0.99,
        imagePaths: ["Merch/sticker1", "Merch/sticker2"],
        description: "It's a sticker featuring the album cover of The Senior Year Blues.",
    },

]
